name: build

on:
  push:
    branches:
      - "branch-*"
    tags:
      - v[0-9][0-9].[0-9][0-9].[0-9][0-9]
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build_type:
        type: string
        default: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda-python-build:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-matrix-build.yaml@main
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      repo: rapidsai/dask-cuda
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
  upload-conda:
    needs: [conda-python-build]
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-upload-packages.yaml@main
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      repo: rapidsai/dask-cuda
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
  wheel-build:
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci:latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Set up environment variables
        run: |
          # While conda provides these during conda-build, they are also necessary during
          # the setup.py build for PyPI
          echo "GIT_DESCRIBE_TAG=`git describe --abbrev=0 --tags`" >> $GITHUB_ENV
          echo "GIT_DESCRIBE_NUMBER=`git rev-list ${GIT_DESCRIBE_TAG}..HEAD --count`" >> $GITHUB_ENV
          # Compute version suffix
          source rapids-env-update
          echo "VERSION_SUFFIX=${VERSION_SUFFIX}" >> $GITHUB_ENV
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to PyPI
        if: inputs.build_type == 'branch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.RAPIDSAI_PYPI_TOKEN }}
