name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - conda-python-build
      - conda-python-tests
      - wheel-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-builder.yaml@main
  checks:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/checks.yaml@main
  conda-python-build:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-matrix-build.yaml@main
    with:
      build_type: pull-request
  conda-python-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-tests.yaml@main
    with:
      build_type: pull-request
  wheel-build:
    uses: rapidsai/dask-cuda/.github/workflows/wheels.yaml@gha
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      repo: rapidsai/dask-cuda
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}